<?php $categories = $this->getCategoryList(); 
$size = $categories->getSize();

/**/
$pages = Mage::getStoreConfig('meetmyteam_option/meetmyteam_all/display_category_page');
if($pages):
//$currentPage = Mage::app()->getRequest()->getRouteName();
$pagesArray = explode(',', $pages);
//if(in_array($currentPage, $pagesArray)):

$currentPage = Mage::helper('core/url')->getCurrentUrl();
$display = false;
foreach ($pagesArray as $value) {
	if (strpos($currentPage,$value) !== false){
		$display = true; // yes page is for display
	}
}
if($display):
/**/	
  

if($size > 0):
?>
<h4>
	<?php echo $this->__('Team Member') ?>
</h4>
<ul>
<?php 
foreach ($categories as $category) {
	echo "<li>";
	$detailUrl = Mage::getUrl('meetmyteam/index/category',array('id'=>$category->getMeetmyteamCatId()));
	echo "<a href='".$detailUrl."'>".$category->getTitle()." </a>";
	echo "</li>";
}
?>
</ul>
<?php endif; ?>

<?php endif; ?>
<?php endif; ?>
