<span class="myteam-head">
<h4>
	<?php echo $this->__('My Team') ?>
</h4>
</span>

<div>
<form id="search_team_form" action="<?php echo Mage::getUrl('meetmyteam')?>" method="get">
    <div class="input-box">
        
        <input id="search-team" type="search" name="q-team" value="<?php if(isset($_GET['q-team'])) echo $_GET['q-team']?>" class="input-text required-entry" maxlength="128" placeholder="Search team by name..." autocomplete="off">
        <button type="submit" title="Search" class="button search-button"><span><span>Search</span></span></button>
    </div>   
</form>
</div>

<?php 
$collection = $this->getAllMembers();

$size = $collection->getSize();

if($size>0){
?>

<div>
<ul class="leader_not"> 
<?php
$url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
	foreach ($collection as $item) {
		$i = $i+1;
//$detailUrl = Mage::getUrl('meetmyteam/index/detail',array('id'=>$item->getId(),'cat_id'=>$item->getCategory()));
$detailUrl = Mage::getUrl('meetmyteam/index/detail',array('id'=>$item->getId()));
$imageUrl = '#';
if($item->getFilename()){
	$imageUrl = $url.'media'.DS.$item->getFilename();
}
?>

<li>

<span class="photo_section">        
<a href="<?php echo $detailUrl; ?>"> <img height="170" width="150" border="0" title="<?php echo $item->getTitle(); ?>" alt="<?php echo $item->getTitle(); ?>" src="<?php echo $imageUrl; ?>"> </a>
</span> 

 <div class="title">
<?php echo $item->getTitle(); ?>
</div> 

<div class="sub-heading"><?php echo $item->getDescription(); ?></div> 

<div class="full-bio"><a href="<?php echo $detailUrl; ?>" class="links">View bio</a></div>
</li>

			
<?php
}
echo "</ul></div>";
}else{
	echo "No any member in this group.";
}


